### ISSUE TITLE
Notification to owner of challenge when someone comments

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1101] opened 2017-11-20 16:47 UTC
As the owner of a challenge, I want to receive an email notification when someone comments on my challenge, so that I know when there is activity that is relevant to me.

On the user settings, we'll need some checkboxes so that people can indicate their preferences or opt out of notifications.

First iteration:
+ We'll have one checkbox to opt in or out of notifications
+ We'll provide some text to explain what the checkbox is for
+ The checkbox will have label "Enable notifications" and well be enabled by default

Because only primary users can create challenges (and thus will be notified), only primary users should see this checkbox for now.

Some question for future iteration:
+ Who should receive a notification? (creator of challenge, all primary contacts of org, also admins)
+ Frequency of notification emails? Every time someone comments, daily, weekly?

**Comment by iteles** [comment] 2017-11-21 08:39
@asimonw As discussed in the sprint planning session yesterday, this requirement will be split into two:
+ For sprint 11, we will ensure that an email is sent out to the challenge owner whenever anyone comments on their challenge _as a default_. This will be accompanied by one simple setting where they get to opt out of emails for comments on their challenge
  + We will need text for the email sent to the members as well as the information that it needs to include (such as a link to the challenge, the organisation of whoever commented (?) and a link to take them straight to the 'opt-out of emails on comments' setting)
  + Design from @fannyBkane on where this unsubscribe/opt-out check box should go and what it should look like
+ 2-4 hour time block to look into email aggregating services that could be used in future
  + It would be great to get a little clarity from you in the issue around where you see the email feature going so this can be taken into account

**Comment by asimonw** [comment] 2017-11-21 10:30
@iteles Where I see the email/notification feature potentially going:
* The option for users to switch to a "regular digest" option, e.g. a weekly email which lists the comments they (and maybe other people from their org) have received.
* Ideally we would be able to easily try out different options. For instance try out different frequencies (daily, weekly, etc). A flexible interface could be useful.
* The digest could include other activities on the app and could grow into a general summary of what happened on the app that week.
* If that's where we go with this, it will become increasingly important to be able to style the emails. One option is for this to follow the usual "designed by Fanny and implemented by dwyl" process, but a simply wysiwyg editor (as provided by some commercial services) for us to use could be a useful and more flexible option.
* Once we have a dashboard, the notification feature will go beyond emails. This includes updates to the dashboard (potentially real-time if there is sufficient traffic). We could also consider push notifications, even though I appreciate that the support for that in desktop browsers is not complete (yet).

**Comment by asimonw** [comment] 2017-11-22 11:40
@iteles Agreed with your suggestion for sprint 11. The information to be included should be:
+ The title of the challenge + a link to the challenge page (the title could be a link, TBC)
+ Name and organisation of person posting the comment (make sure that this is Ellen MacArthur Foundation when it comes from an internal user)
+ The content of the comment
+ A link to the settings page where they can opt out of the notifications

The precise content of the email will be provided towards the end of the week

**Comment by iteles** [comment] 2017-11-27 17:00
Agreed with @asimonw & @fannyBkane Checked status = receiving emails with every comment, and this is checked by default

**Comment by iteles** [comment] 2017-11-27 17:03
Ines to split out spike on email aggregation

**Comment by SimonLab** [comment] 2017-11-29 12:52
- [ x] create new ```notification_email``` boolean column in the ```people``` table with default value to ```true``` :
 ```
ALTER TABLE people ADD COLUMN  notification_email BOOLEAN NOT NULL DEFAULT true;
```

**Comment by SimonLab** [comment] 2017-12-04 15:29
@asimonw ready to be tested on ce100-test. An email will be sent to the creator of the challenge, I will demo the feature this afternoon also

**Comment by asimonw** [comment] 2017-12-04 15:44
Thanks @SimonLab ! A bit late, but this would be the more precise text and title of the email.

Email title: Someone commented on your challenge "<title of challenge>"!

Body
_____

Hello `<first name>`

`<first and last name of commenter>` from `<name of org>` has commented on your challenge! 

Respond to `<first name of commenter>` (make these three words link to challenge) to keep the conversation going or flag the comment for the cello team to review.

**Challenge title**: `<challenge title>`
**Comment**: `<comment text>`

From cello

Too many emails? Change notification settings here (link to settings).

**Comment by asimonw** [comment] 2017-12-05 14:45
@SimonLab This works fine for me 👍 
Could you change the copy I shared above before I close this issue?

**Comment by asimonw** [comment] 2017-12-08 11:02
@SimonLab Sorry, one final tweak to that notification email. Could the text "From cello" towards the end be replaced by "From the CE100 team"?

Once the new name has been approved, we can change that text back. I'll make a note of that in #1146

**Comment by SimonLab** [comment] 2017-12-11 16:55
@asimonw this can now be tested on ce100-test. I've also deployed the latest version on ce100-dam-api but remember that if you add a comment on a challenge an email will be send to the "real" user as this application contains a duplicate of the production app

**Comment by asimonw** [comment] 2017-12-11 17:27
@SimonLab Looks good! The last tweak I mentioned above didn't make it in though. And I didn't catch the other mention of cello, so we actually need two small changes to the text
+ Could the text "From cello" towards the end be replaced by "From the CE100 team"?
+ And higher up in the text, could "for the cello team to review." be replaced by for the CE100 team to review.

**Comment by SimonLab** [comment] 2017-12-11 17:48
@asimonw sorry I just notice that the modification wasn't deployed properly, it should be ok now

**Comment by asimonw** [comment] 2017-12-13 11:00
@SimonLab That looks better, but there's a lot of vertical space between the orgs in the list. It was less before. Would it be possible to revert that?

**Comment by asimonw** [comment] 2017-12-13 11:15
@SimonLab I had indicated two changes to be done and only one was implemented. Could you also make the following change please?
+ And higher up in the text, could "for the cello team to review." be replaced by for the CE100 team to review.

@iteles This fix should also go to production asap.

**Comment by SimonLab** [comment] 2017-12-13 12:54
@asimonw just push a fix on the dam-api app, let me know if it's working

**Closed** 2017-12-13 13:18 UTC
Labels: bug, please-test, primary-user, priority-1, T2h, T4h
