### ISSUE TITLE
When creating/editing an insight, sometimes clicking on add/edit tags returns a 500

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#781] opened 2017-03-07 17:53 UTC
It seems to happen when using a long title, but not consistently, so it's hard to say for sure what's causing it.

Sometimes before the app crashes, it takes up to half a minute to return the 500 page.

**Comment by SimonLab** [comment] 2017-03-07 18:48
Thanks for spotting that @asimonw . I think you are right this is due to the length of the title see https://github.com/postgres-plugin/insights/blob/master/lib/fixtures/create-tables.sql#L4 . The type of the title should be TEXT.
If you are testing on the staging, the app needs a bit of time to start the dyno on heroku that might be why it take a bit of time.

The quickest solution is to manually alter the table insight with psql to change the type to TEXT then to create a PR on the insight plugin to update the type. @mk4111 @JMurphyWeb doesn this seem right?

**Comment by asimonw** [comment] 2017-03-08 10:13
@SimonLab Thanks for looking into this. I'm aware of the "sleep time" of free dynos, but this was after the dyno had "woken up" and the flow was smooth and quick until right before it crashed. It looks like your suggestion might solve both issues though.

**Comment by JMurphyWeb** [comment] 2017-03-09 09:45
We could look into adding db validation layer that flags any failure

**Comment by JMurphyWeb** [comment] 2017-03-09 09:54
${COMMENT}

**Comment by JMurphyWeb** [comment] 2017-03-09 10:01
What do you think @simonLab?

**Comment by JMurphyWeb** [comment] 2017-03-09 10:06
What do you think @simonLab?

**Comment by SimonLab** [comment] 2017-03-09 20:53
@JMurphyWeb I'm not sure we want to limit the length on the title of the insight as it should be able to be long enough.
@asimonw I've just change the type from varchar to text so it should work now.

**Comment by asimonw** [comment] 2017-03-10 14:35
@SimonLab What's the maximum allowed length? It worked with a 100 char string, but not with a 200 char string. Also, after I get the 500 error screen, the app seems to break quite badly. After the "time out" I described before, I see the screen:
<img width="475" alt="screen shot 2017-03-10 at 14 23 41" src="https://cloud.githubusercontent.com/assets/15235804/23798857/4bc584b0-059e-11e7-8567-9d76aabd3f77.png">

It would be fine to agree on a maximum length, although that could be quite large. The app should deal with the exception more elegantly though.

**Comment by SimonLab** [comment] 2017-03-10 15:09
Thanks for testing. There shouldn't be any limit as the type of the title is "TEXT" in the database. I will do more tests and check the logs. I will also check the application timeout and try to reproduce it, I'm wondering if your internet connection might produce the error if it's too slow (but I don't think it should)

**Comment by SimonLab** [comment] 2017-03-10 15:30
I just saw that the database has been reset on the staging with the old type for title, as soon as https://github.com/postgres-plugin/insights/pull/22 is merged the database will have the right type, sorry for the delay it will be a quick fix

**Comment by asimonw** [comment] 2017-03-13 14:49
@SimonLab Just to make sure, changing the type of the field can be done without actually erasing the content, right?

**Comment by asimonw** [comment] 2017-05-19 15:06
@SimonLab This seems to work now, but there is still a harmless but annoying bug. Every time you edit an exist Insight, a few empty spaces are added to the beginning and end of the insight title. This padding doesn't show up in the UI, but is annoying for admins. Could this be prevented, please?

**Comment by SimonLab** [comment] 2017-05-22 10:46
@asimonw I've just clean the white spaces on the inputs, this should be ok now.

**Closed** 2017-05-23 18:15 UTC
Labels: bug, please-test, priority-2, T1h
