### ISSUE TITLE
Hide the current Nav bar menu item drop down when another item is selected

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/ce100-app#1305] opened 2018-05-24 10:26 UTC
When you select a button on the Nav bar, the dropdown does not disappear if you select another button (screenshot attached). We should tweak this so not all menu dropdowns can be selected at the same time
![screen shot 2018-05-24 at 10 26 30](https://user-images.githubusercontent.com/36198201/40480025-2e45de60-5f45-11e8-8b8a-8d3480084fb0.png)

**Comment by asimonw** [comment] 2018-05-25 08:41
@Kimberley-Heath I'm going to close this one, as it's a duplicate of #1259.

I did copy your screen shot into it ;)

**Closed by asimonw** 2018-05-25 08:41 UTC
