### ISSUE TITLE
Browse challenges view with new user created bug

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#274] opened 2016-10-08 13:46 UTC
As in demo, app crashed when browsing. I cannot remember if it was select tags or browse challenges that it crashed on.

I think the error message was: `cannot find .name of undefined.`

Worth looking into the naming of tags. We should use `tagData[id].name` instead of `tag[id].name` ?

Otherwise `organisation.name`?

**Comment by mk4111** [comment] 2016-10-10 15:39
The ```.name of undefined``` error is triggered in browse-view.js, specifically in the addSharedBy fn.
The error doesn't manifest locally but does on heroku - currently adding logs to see what the potential source might be.

**Comment by mk4111** [comment] 2016-10-10 16:35
It _only fails_ when you've _just_ activated your account and you are browsing.

Still failing at addSharedBy though, so where do the sessions info come into play?

**Comment by mk4111** [comment] 2016-10-10 16:42
Doesn't error if you _don't create a new challenge card_...

**Comment by JMurphyWeb** [comment] 2016-10-10 16:59
@mk4111 we filter out the inactive orgs, but any challenge created by an inactive org will still be looked for in the addSharedBy function..

**Comment by mk4111** [comment] 2016-10-10 17:57
@JMurphyWeb - thanks for helping me out! I thought that might be the case too, but I've just added the org and have just checked that both the organisation and challenge are active.

**Comment by JMurphyWeb** [comment] 2016-10-10 18:01
OK but the logic is still wrong. It is causing the problem i'm pretty sure.

**Comment by mk4111** [comment] 2016-10-10 18:03
Let's create another issue on that - it might be the cause of this issue, but I'd like to rule out the other options in mind before I do, as fixing that might complicate fixing this issue

**Comment by JMurphyWeb** [comment] 2016-10-10 18:36
What are the other options you are not sure about?

It doesn't matter if the org and challenge are active, it could still fail as the browsable orgs is a filtered array, referencing it by an index becomes pointless.

**Comment by mk4111** [comment] 2016-10-10 18:37
The issue occurs because we pass in the filtered array, ```browsableOrgs```, instead of the entire array --> the indices of ```browsableOrgs``` don't correspond with the ids of the organisation objects, so when we try to do ```orgs[chal.org_id].name``` where the id is 8 (for a newly created challenge), orgs[8] may not exist, because orgs.length < 8. This explains why the issue wasn't manifesting for existing users adding more challenges

**Comment by mk4111** [comment] 2016-10-10 18:38
@JMurphyWeb - snap!

**Comment by mk4111** [comment] 2016-10-10 19:10
We now have the issue that @JMurphyWeb mentioned above --> will expand in #295

**Comment by mk4111** [comment] 2016-10-11 11:47
Closing issue as fix has been merged into master

**Closed** 2016-10-11 11:48 UTC
Labels: bug, primary-user, T4h, technical
