### ISSUE TITLE
implement good logging into app

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#487] opened 2016-12-15 12:20 UTC
Every time the app crashes, the error is eaten up by hapi-error.  We should set up good console which will allow hapi error to log our errors. Much needed!

**Comment by JMurphyWeb** [comment] 2016-12-15 12:22
@iteles is this technical? the non technical person cannot test it so I think that makes it a non technical (which seems strange 😕 )

**Comment by SimonLab** [comment] 2016-12-15 13:30
This issue is technical as it is focus on developers rather than users.
hapi-error has a [debugging mode](https://github.com/dwyl/hapi-error#debugging) maybe this will give us enough information to track down bugs.

**Comment by SimonLab** [comment] 2016-12-15 13:53
@JMurphyWeb duplicate of #265 ?

**Comment by iteles** [comment] 2016-12-15 23:22
@JMurphyWeb I think you have it exactly backwards! A non-technical person cannot test it (as you correctly say) **so it is a technical task and not a user story**.

**Comment by JMurphyWeb** [comment] 2016-12-16 15:16
right, i must have mis-read your gitter message. That makes a lot more sense.

**Comment by JMurphyWeb** [comment] 2017-01-06 11:47
![screen shot 2017-01-06 at 11 46 08](https://cloud.githubusercontent.com/assets/12638261/21716948/cd22026a-d405-11e6-9fe8-a6f6f66f64a7.png)

This is what the user sees when a Hoek.assert error happens. Nothing is logged in the console.

**Comment by JMurphyWeb** [comment] 2017-01-06 11:49
I have added good console logging into the application. Hapi error should now log a Hoek.assert error:

```
data: {"method":"POST","url":"/people/add","headers":{"host":"localhost:3000","connection":"keep-alive","content-length":"108","cache-control":"max-age=0","origin":"http://localhost:3000","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36","content-type":"application/x-www-form-urlencoded","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","referer":"http://localhost:3000/people/add","accept-encoding":"gzip, deflate, br","accept-language":"en-GB,en-US;q=0.8,en;q=0.6","cookie":"token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImp0aSI6IjUyYzcwNjVmLTAyYWItNDMyZC1hZDEyLTM2ZmUwNzQ1YzgwZSIsImlhdCI6MTQ4MzcwMzA2Mjg5OH0.tVM3ctAs07_2cuKypMXP8YAay9wiDNr1xPXK1NaEPQM"},"info":{"received":1483703084626,"responded":0,"remoteAddress":"127.0.0.1","remotePort":56496,"referrer":"http://localhost:3000/people/add","host":"localhost:3000","acceptEncoding":"gzip","hostname":"localhost"},"auth":{"isAuthenticated":true,"credentials":{"scope":"admin","organisation_id":null,"userId":2,"jti":"52c7065f-02ab-432d-ad12-36fe0745c80e","iat":1483703062898},"artifacts":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImp0aSI6IjUyYzcwNjVmLTAyYWItNDMyZC1hZDEyLTM2ZmUwNzQ1YzgwZSIsImlhdCI6MTQ4MzcwMzA2Mjg5OH0.tVM3ctAs07_2cuKypMXP8YAay9wiDNr1xPXK1NaEPQM","strategy":"jwt2","mode":"required","error":null,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImp0aSI6IjUyYzcwNjVmLTAyYWItNDMyZC1hZDEyLTM2ZmUwNzQ1YzgwZSIsImlhdCI6MTQ4MzcwMzA2Mjg5OH0.tVM3ctAs07_2cuKypMXP8YAay9wiDNr1xPXK1NaEPQM"},"email":"","payload":{"first_name":"asdf","last_name":"asdf","job_title":"asdf","email":"ma@ka.co","phone":"74225164088","user_type":"primary","org_id":-1},"response":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}}
```

**Comment by JMurphyWeb** [comment] 2017-01-06 11:57
The error message of `"Cannot read property 0 of undefined"` and the stack trace are not logged.

@SimonLab do you know if we should be expecting to see the error message and stack trace in the logs? The primary reason we wanted to implement this feature was to better understand the error when we have one.

**Comment by JMurphyWeb** [comment] 2017-01-06 12:28
I have dug into the hapi error source code and seen that it does not attach the error stack trace to the logged object:
```js
  debug = {
        method: req.method, // e.g GET/POST
        url: request.url.path, // the path the person requested
        headers: request.raw.req.headers, // all HTTP Headers
        info: request.info, // all additional request info (useful for debug)
        auth: request.auth, // any authentication details e.g. the decoded JWT
        email: request.auth.credentials && request.auth.credentials.email
          ? request.auth.credentials.email : '', // see: https://git.io/vPZBK
        payload: request.payload, // the complete request payload received
        response: res.output.payload // response before error intercepted
      };
```

**Comment by JMurphyWeb** [comment] 2017-01-06 13:14
have issued in hapi error: https://github.com/dwyl/hapi-error/issues/43

**Closed** 2017-01-11 12:18 UTC
Labels: enhancement, in-review, T1h, technical
